
# tap repositories and their packages

tap homebrew/core
brew asdf
brew bat
brew clipboard
brew cmake
brew dfc
brew fd
brew ffmpeg
brew fish
brew fzf
brew gawk
brew gh
brew git
brew git-delta
brew htop
brew jq
brew libyaml
brew lsd
brew mackup
brew mas
brew midnight-commander
brew ncdu
brew neovim
brew openjdk
brew sk
brew thefuck
brew tlrc
brew tmux
brew tree
brew uv
brew watch
brew watchman
brew wget
brew wtf
brew yadm
brew yazi
brew yt-dlp
brew zoxide

tap homebrew/cask
cask android-commandlinetools
cask appcleaner
cask chatgpt
cask claude
cask codex
cask codexbar
cask contexts
cask cursor
cask daisydisk
cask deepl
cask figma
cask fluor
cask flux-app
cask font-hack-nerd-font
cask ghostty
cask google-chrome
cask iina
cask iterm2
cask jetbrains-toolbox
cask jordanbaird-ice@beta
cask logi-options+
cask macmediakeyforwarder
cask obsidian
cask plex
cask pxplay
cask qlmarkdown
cask qlvideo
cask raycast
cask reader
cask rustdesk
cask screens-connect
cask setapp
cask spotify
cask syntax-highlight
cask visual-studio-code
cask xcodes-app

tap rcmdnk/file
brew brew-file

tap buo/cask-upgrade

tap steipete/tap
brew gogcli
brew peekaboo
brew sag
brew summarize

tap teamookla/speedtest
brew speedtest

# App Store applications
appstore 1206020918 Battery Indicator (2.19.0)
appstore 1397180934 Dark Mode for Safari (3.6.1)
appstore 1470584107 Dato (5.6.2)
appstore 1388020431 DevCleaner (2.7.1)
appstore 1544743900 Hush (1.0.17)
appstore 470158793 Keka (1.5.2)
appstore 441258766 Magnet (3.0.7)
appstore 905953485 NordVPN (9.2.1)
appstore 409203825 Numbers (14.4)
appstore 1188020834 OverPicture (2.5)
appstore 409201541 Pages (14.4)
appstore 6714467650 Perplexity (2.250724.0)
appstore 6738274497 Raycast Companion (1.1.1)
appstore 1086818840 Rocket.Chat (4.7.1)
appstore 747648890 Telegram (11.15)
appstore 966085870 TickTick (6.3.40)
appstore 1547912640 uBlacklist for Safari (9.1.0)
appstore 1637438059 UnTrap (87)
appstore 1463298887 Userscripts (4.8.1)
appstore 1607635845 Velja (2.1.3)
appstore 1662217862 Wipr (2.9.5)
appstore 1451685025 WireGuard (1.0.16)

cursor "astro-build.astro-vscode"
cursor "bradlc.vscode-tailwindcss"
cursor "dbaeumer.vscode-eslint"
cursor "edwinhuish.better-comments-next"
cursor "esbenp.prettier-vscode"
cursor "github.github-vscode-theme"
cursor "k--kato.intellij-idea-keybindings"
cursor "oven.bun-vscode"
cursor "usernamehw.errorlens"
cursor "yoavbls.pretty-ts-errors"
